Use Module.const_get instead of String#constantize
This fixes an incompatibility between major versions of Rails.

    # Rails 3.2
    >> ''.constantize
    => Object

    # Rails 4.1
    >> ''.constantize
    NameError: wrong constant name